name: shikamo
version: '0.1.0.0'
category: Compiler
author: Providence Salumu
maintainer: Providence.Salumu@smunix.com
copyright: BSD
license: BSD3
github: smunix/shikamo
extra-source-files:
- README.md

executables:
  shikamo:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - shikamo
    default-extensions:
    - CPP
    - GADTs
    - DataKinds
    - DeriveGeneric

library:
  source-dirs: src
  exposed-modules:
  - Data.String.Strip
  - Shikamo.Parse.Parser
  - Shikamo.Lang.Expr
  - Shikamo.Lexer.Lexer
  - Shikamo.Lexer.Loc
  dependencies:
  - base
  - deepseq
  - exceptions
  - hashable
  - mtl
  - parsec
  - repline
  - text
  - unordered-containers
  default-extensions:
  - ConstraintKinds
  - CPP
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveDataTypeable
  - DeriveTraversable
  - EmptyDataDeriving
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - KindSignatures
  - MultiParamTypeClasses
  - PolyKinds
  - LambdaCase
  - MultiWayIf
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies

tests:
  shikamo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - shikamo
    - hspec
    - QuickCheck
    - hashable
    - parsec
    - repline
    - text
    - unordered-containers
    default-extensions:
    - CPP
    - GADTs
    - DataKinds
    - DeriveGeneric
    - OverloadedStrings
    - ScopedTypeVariables
    - StandaloneDeriving
